spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000

app:
  security:
    type: db #inMemory
    users:
      - username: "user"
        password: "12345"
        roles: [ "USER" ]
      - username: "admin"
        password: "11111"
        roles: [ "USER", "ADMIN" ]